name: Filled
on:
  repository_dispatch:
    types: ['filled']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Config node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: make init
      - name: Starting message
      - uses: Nologis/slack-message-github-action@v1.2.1
        env:
          WEBHOOK_URL: ${{secrets.SLACK_RELEASES_WEBHOOK_URL}}
          SLACK_CHANNEL: woffu
          MESSAGE: ⏰ ${{github.event.client_payload.email}} Starting to fill the hours!! ⏰
#      - name: Filled
#        env:
#          EMAIL: ${{ github.event.client_payload.email }}
#          PASSWORD: ${{ github.event.client_payload.password }}
#        run: ./.scripts/filled-action.sh
      - name: Finishing message
      - uses: Nologis/slack-message-github-action@v1.2.1
        env:
          WEBHOOK_URL: ${{secrets.SLACK_RELEASES_WEBHOOK_URL}}
          SLACK_CHANNEL: woffu
          MESSAGE: ⏰ ${{github.event.client_payload.email}} thanks for update your hours!! ⏰