name: Filled
on:
  repository_dispatch:
    types: ['filled']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Config node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: make init
      - name: Starting message
        env:
          WEBHOOK_URL: ${{ secrets.WOFFU_SLACK_WEBHOOK_URL }}
          MESSAGE: ⏰ ${{ github.event.client_payload.email }} Starting to fill the hours!! ⏰
        run: ./.scripts/test.sh start
#      - name: Filled
#        env:
#          EMAIL: ${{ github.event.client_payload.email }}
#          PASSWORD: ${{ github.event.client_payload.password }}
#        run: ./.scripts/filled-action.sh
      - name: Finishing message
        env:
          WEBHOOK_URL: ${{ secrets.WOFFU_SLACK_WEBHOOK_URL }}
          MESSAGE: ⏰ ${{ github.event.client_payload.email }} thanks for update your hours!! ⏰
        run: ./.scripts/test.sh