name: Filled
on:
  repository_dispatch:
    types: ['filled']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Config node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: make init
      - name: Filled
        run: ./.scripts/filled-action.sh "${{ github.event.client_payload.email }}" "${{ github.event.client_payload.password }}"
